In [1]:
import pandas

from bokeh.layouts import column
from bokeh.models import ColumnDataSource,RangeTool
from bokeh.plotting import figure,output_file,show

In [2]:
df = pandas.read_html('https://coinmarketcap.com/currencies/bitcoin/historical-data/?start=20190220&end=20190320')

In [3]:
df

[            Date    Open*     High      Low  Close**       Volume   Market Cap
 0   Mar 20, 2019  4070.79  4089.46  4031.11  4087.48  10175916388  71942444088
 1   Mar 19, 2019  4032.69  4082.22  4023.81  4071.19   9344919956  71647703828
 2   Mar 18, 2019  4029.97  4071.56  4009.12  4032.51   9646954186  70958165407
 3   Mar 17, 2019  4047.72  4054.12  4006.41  4025.23   8221625400  70821939585
 4   Mar 16, 2019  3963.90  4077.04  3961.66  4048.73   9856166973  71227967573
 5   Mar 15, 2019  3926.66  3968.54  3914.02  3960.91   9394210605  69675002377
 6   Mar 14, 2019  3905.58  3946.50  3901.30  3924.37  10480789570  69024696307
 7   Mar 13, 2019  3913.05  3926.60  3891.90  3906.72   9469184841  68706700381
 8   Mar 12, 2019  3903.76  3926.89  3863.56  3909.16   9809887079  68743000581
 9   Mar 11, 2019  3953.74  3966.38  3889.24  3905.23  10125901903  68666928025
 10  Mar 10, 2019  3966.17  3966.17  3924.38  3951.60   9713267607  69475297370
 11  Mar 09, 2019  3894.55  3987.24  3892.39  3963.31  10796103518  69674508655
 12  Mar 08, 2019  3913.23  3950.43  3875.23  3901.13  10638638944  68574579320
 13  Mar 07, 2019  3903.38  3939.37  3894.11  3911.48   9584165519  68749421311
 14  Mar 06, 2019  3897.08  3919.51  3871.46  3903.94   9175291529  68609885776
 15  Mar 05, 2019  3759.83  3903.92  3745.18  3896.38  10174126415  68470655400
 16  Mar 04, 2019  3845.09  3867.38  3733.75  3761.56   9029175788  66094551587
 17  Mar 03, 2019  3862.27  3875.48  3836.91  3847.18   7253558152  67592376373
 18  Mar 02, 2019  3855.32  3874.61  3832.13  3864.42   7578786076  67888255371
 19  Mar 01, 2019  3853.76  3907.80  3851.69  3859.58   7661247975  67796965743
 20  Feb 28, 2019  3848.26  3906.06  3845.82  3854.79   8399767798  67704774107
 21  Feb 27, 2019  3857.48  3888.80  3787.06  3851.05   8301309684  67631949500
 22  Feb 26, 2019  3878.70  3891.58  3837.99  3854.36   7931218996  67683296223
 23  Feb 25, 2019  3807.00  3913.71  3807.00  3882.70   9318796067  68173204651
 24  Feb 24, 2019  4145.46  4210.64  3793.71  3810.43  10794227451  66897483404
 25  Feb 23, 2019  3998.92  4166.29  3968.73  4142.53   8922258316  72720867208
 26  Feb 22, 2019  3952.41  4006.54  3950.82  4005.53   7826525254  70308555857
 27  Feb 21, 2019  4000.26  4010.01  3940.11  3954.12   7775128102  69398333876
 28  Feb 20, 2019  3946.68  4000.49  3926.25  3999.82   8693373948  70194350042,
                            0                            1
 0              Bitcoin Price                  8264.49 USD
 1                Bitcoin ROI                    +6008.27%
 2                Market Rank                           #1
 3                 Market Cap          148,503,343,569 USD
 4             24 Hour Volume           14,441,583,192 USD
 5         Circulating Supply               17,968,850 BTC
 6               Total Supply               17,968,850 BTC
 7                 Max Supply               21,000,000 BTC
 8              All Time High  20089.00 USD (Dec 17, 2017)
 9               All Time Low     65.53 USD (Jul 05, 2013)
 10        52 Week High / Low   13796.49 USD / 3191.30 USD
 11         90 Day High / Low   13129.53 USD / 7830.76 USD
 12         30 Day High / Low   10898.76 USD / 7830.76 USD
 13          7 Day High / Low    8648.19 USD / 7830.76 USD
 14        24 Hour High / Low    8497.69 USD / 8227.70 USD
 15    Yesterday's High / Low    8497.69 USD / 8232.68 USD
 16  Yesterday's Open / Close    8299.72 USD / 8343.28 USD
 17        Yesterday's Change          $43.56 USD (+0.52%)
 18        Yesterday's Volume          $15,305,343,413 USD]

在這個網頁裡面有兩個表格，所以在 df 回傳回來的值就會有兩個，但只要第一個表格，所以要用 index[0] 的方式，來回傳第一個表格。

此外，第一個表格的時間，是從 3/20 到 2/20，和所想要的時間順序是相反的，所以要用 [::-1] 的方式，全選表格後，進行反轉。

In [4]:
df = pandas.read_html('https://coinmarketcap.com/currencies/bitcoin/historical-data/?start=20190220&end=20190320')[0][::-1]

In [5]:
df

            Date    Open*     High      Low  Close**       Volume   Market Cap
28  Feb 20, 2019  3946.68  4000.49  3926.25  3999.82   8693373948  70194350042
27  Feb 21, 2019  4000.26  4010.01  3940.11  3954.12   7775128102  69398333876
26  Feb 22, 2019  3952.41  4006.54  3950.82  4005.53   7826525254  70308555857
25  Feb 23, 2019  3998.92  4166.29  3968.73  4142.53   8922258316  72720867208
24  Feb 24, 2019  4145.46  4210.64  3793.71  3810.43  10794227451  66897483404
23  Feb 25, 2019  3807.00  3913.71  3807.00  3882.70   9318796067  68173204651
22  Feb 26, 2019  3878.70  3891.58  3837.99  3854.36   7931218996  67683296223
21  Feb 27, 2019  3857.48  3888.80  3787.06  3851.05   8301309684  67631949500
20  Feb 28, 2019  3848.26  3906.06  3845.82  3854.79   8399767798  67704774107
19  Mar 01, 2019  3853.76  3907.80  3851.69  3859.58   7661247975  67796965743
18  Mar 02, 2019  3855.32  3874.61  3832.13  3864.42   7578786076  67888255371
17  Mar 03, 2019  3862.27  3875.48  3836.91  3847.18   7253558152  67592376373
16  Mar 04, 2019  3845.09  3867.38  3733.75  3761.56   9029175788  66094551587
15  Mar 05, 2019  3759.83  3903.92  3745.18  3896.38  10174126415  68470655400
14  Mar 06, 2019  3897.08  3919.51  3871.46  3903.94   9175291529  68609885776
13  Mar 07, 2019  3903.38  3939.37  3894.11  3911.48   9584165519  68749421311
12  Mar 08, 2019  3913.23  3950.43  3875.23  3901.13  10638638944  68574579320
11  Mar 09, 2019  3894.55  3987.24  3892.39  3963.31  10796103518  69674508655
10  Mar 10, 2019  3966.17  3966.17  3924.38  3951.60   9713267607  69475297370
9   Mar 11, 2019  3953.74  3966.38  3889.24  3905.23  10125901903  68666928025
8   Mar 12, 2019  3903.76  3926.89  3863.56  3909.16   9809887079  68743000581
7   Mar 13, 2019  3913.05  3926.60  3891.90  3906.72   9469184841  68706700381
6   Mar 14, 2019  3905.58  3946.50  3901.30  3924.37  10480789570  69024696307
5   Mar 15, 2019  3926.66  3968.54  3914.02  3960.91   9394210605  69675002377
4   Mar 16, 2019  3963.90  4077.04  3961.66  4048.73   9856166973  71227967573
3   Mar 17, 2019  4047.72  4054.12  4006.41  4025.23   8221625400  70821939585
2   Mar 18, 2019  4029.97  4071.56  4009.12  4032.51   9646954186  70958165407
1   Mar 19, 2019  4032.69  4082.22  4023.81  4071.19   9344919956  71647703828
0   Mar 20, 2019  4070.79  4089.46  4031.11  4087.48  10175916388  71942444088

In [6]:
df['Date'] = pandas.to_datetime(df['Date'])

In [7]:
df

         Date    Open*     High      Low  Close**       Volume   Market Cap
28 2019-02-20  3946.68  4000.49  3926.25  3999.82   8693373948  70194350042
27 2019-02-21  4000.26  4010.01  3940.11  3954.12   7775128102  69398333876
26 2019-02-22  3952.41  4006.54  3950.82  4005.53   7826525254  70308555857
25 2019-02-23  3998.92  4166.29  3968.73  4142.53   8922258316  72720867208
24 2019-02-24  4145.46  4210.64  3793.71  3810.43  10794227451  66897483404
23 2019-02-25  3807.00  3913.71  3807.00  3882.70   9318796067  68173204651
22 2019-02-26  3878.70  3891.58  3837.99  3854.36   7931218996  67683296223
21 2019-02-27  3857.48  3888.80  3787.06  3851.05   8301309684  67631949500
20 2019-02-28  3848.26  3906.06  3845.82  3854.79   8399767798  67704774107
19 2019-03-01  3853.76  3907.80  3851.69  3859.58   7661247975  67796965743
18 2019-03-02  3855.32  3874.61  3832.13  3864.42   7578786076  67888255371
17 2019-03-03  3862.27  3875.48  3836.91  3847.18   7253558152  67592376373
16 2019-03-04  3845.09  3867.38  3733.75  3761.56   9029175788  66094551587
15 2019-03-05  3759.83  3903.92  3745.18  3896.38  10174126415  68470655400
14 2019-03-06  3897.08  3919.51  3871.46  3903.94   9175291529  68609885776
13 2019-03-07  3903.38  3939.37  3894.11  3911.48   9584165519  68749421311
12 2019-03-08  3913.23  3950.43  3875.23  3901.13  10638638944  68574579320
11 2019-03-09  3894.55  3987.24  3892.39  3963.31  10796103518  69674508655
10 2019-03-10  3966.17  3966.17  3924.38  3951.60   9713267607  69475297370
9  2019-03-11  3953.74  3966.38  3889.24  3905.23  10125901903  68666928025
8  2019-03-12  3903.76  3926.89  3863.56  3909.16   9809887079  68743000581
7  2019-03-13  3913.05  3926.60  3891.90  3906.72   9469184841  68706700381
6  2019-03-14  3905.58  3946.50  3901.30  3924.37  10480789570  69024696307
5  2019-03-15  3926.66  3968.54  3914.02  3960.91   9394210605  69675002377
4  2019-03-16  3963.90  4077.04  3961.66  4048.73   9856166973  71227967573
3  2019-03-17  4047.72  4054.12  4006.41  4025.23   8221625400  70821939585
2  2019-03-18  4029.97  4071.56  4009.12  4032.51   9646954186  70958165407
1  2019-03-19  4032.69  4082.22  4023.81  4071.19   9344919956  71647703828
0  2019-03-20  4070.79  4089.46  4031.11  4087.48  10175916388  71942444088

將原本輸出的 Date 時間，轉變為適當的時間格式，並會直接取代掉原本在 df 的 Date。

In [8]:
dates = df['Date'].to_numpy(dtype = 'datetime64[D]')

將適當的時間格式，轉變為 numpy 的時間格式，在datetime64[] 裡面可以放入其它字元，就會顯示出不同的結果。

1. s 會直接顯示到秒。
2. m 會直接顯示到分。
3. h 會直接顯示到時。
4. D 會直接顯示到日。
5. M 會直接顯示到月。
6. Y 會直接顯示到年。

在秒，分，時這三個，都要用小寫，在年月日這三個，都要用大寫。

In [9]:
dates

array(['2019-02-20', '2019-02-21', '2019-02-22', '2019-02-23',
       '2019-02-24', '2019-02-25', '2019-02-26', '2019-02-27',
       '2019-02-28', '2019-03-01', '2019-03-02', '2019-03-03',
       '2019-03-04', '2019-03-05', '2019-03-06', '2019-03-07',
       '2019-03-08', '2019-03-09', '2019-03-10', '2019-03-11',
       '2019-03-12', '2019-03-13', '2019-03-14', '2019-03-15',
       '2019-03-16', '2019-03-17', '2019-03-18', '2019-03-19',
       '2019-03-20'], dtype='datetime64[D]')

In [10]:
source = ColumnDataSource(data = dict(data = dates, close = list(df["Close**"])))

對應到資料，在 data 的部分，就是對應到日期，在 close 的部分，就是對應到表格內的 close** 這部分。

In [11]:
# 高度是 300
# 寬度是 1200
# 將預設的工具欄隱藏
# x軸資料為datetime
# x軸位置為上方（預設為下方）
# 背景填滿色為 #efefef
# 在圖表製作完後，x軸顯示預設的範圍為 2019-03-04 到 2019-03-12

p = figure(plot_height = 300, plot_width = 1200, tools = '', toolbar_location = None,x_axis_type ='datetime',x_axis_location = 'above',background_fill_color = '#efefef',x_range = (dates[12],dates[20]))

In [12]:
p.line('data','close',source = source)

GlyphRenderer(id='1025', ...)

In [13]:
# y軸圖例顯示為 price
p.yaxis.axis_label = 'Price'

In [14]:
select = figure(title = 'Drag the middle and edges of selection box to change the range above',plot_height = 130,plot_width = 1200,y_range = p.y_range,x_axis_type = 'datetime',y_axis_type = None,tools = '',toolbar_location = None,background_fill_color = '#efefef')

In [15]:
range_tool = RangeTool(x_range = p.x_range)

In [16]:
range_tool.overlay.fill_color = 'navy'
range_tool.overlay.fill_alpha = 0.2

In [17]:
select.line('data','close',source = source)

GlyphRenderer(id='1051', ...)

In [18]:
select.ygrid.grid_line_color = None

In [19]:
select.add_tools(range_tool)

In [20]:
# 可以有多個動作，就像是選取起點跟終點
select.toolbar.active_multi = range_tool

In [21]:
output_file('btc_range.html',title = 'Bitcoin Price Chart')

In [22]:
# 將兩個圖表，當作是欄位，讓他們上面對齊，並顯示出來
show(column(p, select))